### PR TITLE
Add capabilities property

### PR DESCRIPTION
**Pull request by phillmac**
Define what optional functions are actually implemented in this controller, e.g. grant / revoke as a public static property

### CODE REVIEW

**Comment by shamb0t** [comment]
@phillmac Thanks for opening a PR. Can you elaborate on what you're trying to accomplish?

Also note that none of the access controllers currently support key revocation

**Comment by phillmac** [comment]
Basically from the api standpoint, I have no visibility into the grant / revoke functions that are actually present on a given controller.  It'd be useful to have the ability to report for e.g. If this controller has `grant` implemented.

**Comment by shamb0t** [comment]
@phillmac could the same be achieved by calling the capability of interest in a `try-catch` block in the http-api? Not all access-controllers are required to adhere to those capabilities, and if others are added wouldn't it require listing them all in the interface?

**Comment by phillmac** [comment]
@shamb0t If the functions were just purely undefined that'd be great, because the error would be feedback that the api call failed.
Currently the functions defined in the `access-controller-interface` silently return and to all apearances the api call suceeded.
See https://github.com/orbitdb/orbit-db-http-api/issues/20

**Comment by phillmac** [comment]
As you said there would be some interface overhead in maintaining a list of what controllers have what functions. A better solution would be very welcome!

**Comment by shamb0t** [comment]
@phillmac ah yes ofc they are already in the interface....hmm perhaps a quick fix could be changing `grant` and `revoke` in the interface to return false instead of a noop? That way if its not overridden as in the `ipfs-access-controller` case it will return false

**Comment by phillmac** [comment]
That'd be a lot better. I'll make another pr and close this one?

**Comment by shamb0t** [comment]
@phillmac that would be great!

**Pull request closed without merging**
